apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
  namespace: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wikibase-local-root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: wikibase-local-root-ca
  secretName: wikibase-local-root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: wikibase-local-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: wikibase-local-root-secret
