apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "queryservice-updater.fullname" . }}
  labels:
{{ include "queryservice-updater.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "queryservice-updater.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "queryservice-updater.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: WBSTACK_LOOP_LIMIT
              value: {{ .Values.app.loopLimit| quote }}
            - name: EXTRA_JVM_OPTS
              # https://medium.com/adorsys/usecontainersupport-to-the-rescue-e77d6cfea712
              # https://merikan.com/2019/04/jvm-in-a-container/
              # http://www.mastertheboss.com/java/solving-java-lang-outofmemoryerror-metaspace-error/
              value: {{ .Values.app.extraJvmOpts | quote }}
              #value: "-XshowSettings:vm -XX:+UseContainerSupport -XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=80.0 -XX:MaxMetaspaceSize=30m -XX:+UseSerialGC -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Dcom.sun.management.jmxremote -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.rmi.port=1099 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
            - name: GC_LOGS
              value: " "
            - name: WBSTACK_BATCH_SLEEP
              value: {{ .Values.app.sleepTime| quote }}
            - name: WBSTACK_API_ENDPOINT
              value: {{ .Values.app.getBatchesEndpoint | quote }}
            - name: WBSTACK_WIKIBASE_SCHEME
              value: {{ .Values.app.wikibaseScheme | quote }}
            - name: WBSTACK_PROXYMAP_INGRESS
              value: {{ .Values.app.proxyMap | quote }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
