apiVersion: v1
kind: Service
metadata:
  name: {{ include "anubis.fullname" . }}
  labels:
    {{- include "anubis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.port.metrics }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "anubis.selectorLabels" . | nindent 4 }}
