apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wdqs.fullname" . }}-allowlist
data:
  allowlist-static.txt:
    {{- .Values.allowListStatic | toYaml | indent 2 }}
  allowlist.txt:
    {{- .Values.allowList | toYaml | indent 2 }}
