apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-sidecar-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 8080;
  
        location /allowlist.txt {
          root /wdqs/;
        }
      }
    }
