{{- if .Values.restorePodRunning }}
apiVersion: v1
kind: Pod
metadata:
  name: restore-sql-logic-backup
spec:
  containers:
  - name: restore-sql-logic-backup
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    resources:
      {{- toYaml .Values.resources.restorePod | nindent 6 }}
{{ include "backup.sharedPodConfiguration" ( dict "db" .Values.db.load "context" $ ) | nindent 4 }}
{{ include "backup.sharedVolumes" ( dict "storage" .Values.storage ) | nindent 2 }}
  restartPolicy: Never

{{- end }}