apiVersion: v2
name: argocd-apps
description: Chart to deploy WBaaS apps in an "app-of-apps" pattern via ArgoCD
type: application
version: 1.0.6
appVersion: "1.0"
maintainers:
  - name: WBstack
    url: https://github.com/wbstack
