apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "api.fullname" . }}-defaultrole
  labels:
{{ include "api.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "api.fullname" . }}-defaultrole
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ include "api.fullname" . }}-defaultrole
  apiGroup: rbac.authorization.k8s.io
