apiVersion: v1
appVersion: "1.0"
description: A Helm chart for the WBStack API
name: api
version: 0.15.0
home: https://github.com/wbstack
maintainers:
  - name: WBstack
    url: https://github.com/wbstack
