{{- if .Values.web.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "mediawiki.fullname" . }}-app-web
  namespace: default
spec:
  maxReplicas: {{ .Values.web.autoscaling.maxReplicas }}
  minReplicas: {{ .Values.web.autoscaling.minReplicas }}
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "mediawiki.fullname" . }}-app-web
{{- end}}