apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: queryservice-updater
version: 0.1.1
home: https://github.com/wbstack
maintainers:
  - name: WBstack
    url: https://github.com/wbstack
